version: '3.7'
services:
  webapp:
    depends_on:
      - db
    image: humanlib-webadmin:lates
    container_name: humanlib-webadmin
    ports:
      - '8081:8080'
  respapi:
    depends_on:
      - db
    image: humanlib-restapi:lates
    container_name: humanlib-restapi
    ports:
      - '8080:8080'
  db:
    image: postgres:11.2-alpine
    container_name: humanlib-db
    environment:
      POSTGRES_USER: 'humanlib'
      POSTGRES_PASSWORD: 'lib123'
      POSTGRES_DB: 'humanlib'
    expose:
      - "5432"
    restart: always